sysed: fix some bugs

diff --git a/sysed b/sysed
--- a/sysed
+++ b/sysed
@@ -141,7 +141,7 @@ mode_backup() {
 		mount ${DEVLV}/${LV}-snapshot ${mountpoint}
 
 		tar --create --use-compress-prog=pigz --same-permissions \
-		--file ${SAVE_PATH}/${SAVE_NAME}.tar.gz ${mountpoint}
+		--file ${SAVE_PATH}/${SAVE_NAME}.tar.gz -C ${mountpoint} --exclude="lost+found" .
 
 		umount ${mountpoint}
 		rm -rf ${mountpoint}
@@ -165,9 +165,10 @@ mode_restore() {
 	if ((${CALCULATE_SIZE})); then
 		pigz -d ${RESTORE_FILE} | dd of="${DEVLV}/${NAME}"
 	else
+		mkfs -t ${FS} -q ${DEVLV}/${NAME}
 		local mountpoint="/tmp/mp-${RANDOM}"
 		mkdir -p "${mountpoint}"
-		mount ${DEVLV}/${LV}-snapshot ${mountpoint}
+		mount ${DEVLV}/${NAME} ${mountpoint}
 
 		tar xvpfz ${RESTORE_FILE} -C "${mountpoint}"
 
@@ -286,6 +287,7 @@ usage() {
 	echo "Restore Options"
 	echo -e " -n|--name [NAME]\tnew name of the sys (DEFAULT: filename)"
 	echo -e " -s|--size [SIZE]\tfor tar.gz files, SIZE of the lv must be provided"
+	echo -e " -f|--fs\t\t\troot filestyem type"
 	echo
 	echo "Edit Options"
 	echo -e " -x|--remove\t\tRemove files from given lvs"
@@ -391,6 +393,7 @@ while true ; do
 			case "$2" in
 				"") shift 2 ;;
 				*) SIZE="${2}" ; shift 2 ;;
+			esac ;;
 		-v|--lv)
 			case "$2" in
 				"") shift 2 ;;
@@ -484,7 +487,7 @@ case "$MODE" in
 		[ -z ${SAVE_PATH} ] && SAVE_PATH=`pwd`
 		[ -z ${SAVE_NAME} ] && SAVE_NAME="${LV}"
 
-		if [ -d ${SAVE_PATH} ]; then echo "\"${SAVE_PATH}\" doesn't exist. Exit!"; exit 1; fi
+		if ! [ -d ${SAVE_PATH} ]; then echo "\"${SAVE_PATH}\" doesn't exist. Exit!"; exit 1; fi
 		if ! [ -w ${SAVE_PATH} ]; then echo "No write permissions on \"${SAVE_PATH}\". Exit!"; exit 1; fi
 		if [ -e "${SAVE_PATH}/${SAVE_NAME}.gz" ]; then read -p "File exists. Overwrite? (Ctrl-C for cancel!)"; fi
 
@@ -497,11 +500,20 @@ case "$MODE" in
 		if ! [ -e ${RESTORE_FILE} ]; then echo "File doesn't exsist. Exit!"; exit 1; fi
 
 		if [ "${FEXT1}" == "tar.gz" ] || [ "${FEXT2}" == "tgz" ]; then
+			if [ -z ${FS} ]; then
+				echo "No Filesystem given. Exit!"
+				exit 1
+			else
+				if ! [ ${FS} == "ext2" ] && ! [ ${FS} == "ext3" ] && ! [ ${FS} == "ext4" ] && ! [ ${FS} == "jfs" ]; then
+					echo "\"${FS}\": Invalid fs. Supported are: ext2, ext3, ext4, jfs"
+					exit 1
+				fi
+			fi
 			if [ -z ${SIZE} ]; then
 				echo "No Size given. Exit!"
 				exit 1
 			else
-				if ! [ "${SIZE: -1}" -eg "G" ]; then
+				if ! [ "${SIZE: -1}" == "G" ]; then
 					SIZE="${SIZE}G"
 				fi
 			fi
